import { useMemo, useState } from "react";
import { Boxes, MapPin, Search, TriangleAlert } from "lucide-react";
import { useListCentres } from "@workspace/api-client-react";
import { Button, EmptyState, QueryError, QueryLoading, StatusPill } from "@/components/ui-kit";

export default function Centres() {
  const centres = useListCentres();
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState("All centres");
  const items = useMemo(() => (centres.data ?? []).filter((item) => item.name.toLowerCase().includes(search.toLowerCase()) && (filter === "All centres" || item.status === filter)), [centres.data, search, filter]);
  return <section className="mx-auto max-w-[1440px] p-5 sm:p-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="font-mono text-[11px] uppercase tracking-[.18em] text-primary">Network capacity</p><h1 className="mt-2 font-display text-4xl font-bold tracking-[-.04em]">Collection centres</h1><p className="mt-2 text-sm text-muted-foreground">Know what each location can hold before it asks for a pickup.</p></div><div className="flex items-center gap-2 rounded-xl border border-border bg-card px-3 py-2 text-sm font-semibold"><Boxes className="h-4 w-4 text-primary" /> {items.length} locations visible</div></div>
    <div className="mt-8 flex flex-col gap-3 sm:flex-row"><div className="relative flex-1 sm:max-w-sm"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><input data-testid="input-search-centres" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Find a centre" className="w-full rounded-xl border border-input bg-card py-3 pl-9 pr-3 text-sm outline-none focus:ring-2 focus:ring-ring" /></div><select data-testid="select-centre-status" value={filter} onChange={(e) => setFilter(e.target.value)} className="rounded-xl border border-input bg-card px-3 py-3 text-sm font-semibold outline-none"><option>All centres</option><option>Active</option><option>Near threshold</option><option>Full</option></select></div>
    {centres.isLoading ? <div className="mt-6"><QueryLoading rows={4} /></div> : centres.isError ? <div className="mt-6"><QueryError onRetry={() => centres.refetch()} /></div> : items.length === 0 ? <div className="mt-6"><EmptyState title="No centres found" detail="Try broadening your search or status filter." /></div> : <div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map((centre) => { const fill = Math.min(100, centre.capacity ? centre.currentQuantity / centre.capacity * 100 : centre.thresholdPercent); const isCritical = fill >= centre.thresholdPercent; return <article data-testid={`card-centre-${centre.id}`} key={centre.id} className="hover-elevate rounded-2xl border border-card-border bg-card p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><h2 className="font-display text-xl font-bold">{centre.name}</h2><p className="mt-1 flex items-center gap-1 text-xs text-muted-foreground"><MapPin className="h-3.5 w-3.5" />{centre.address}</p></div><StatusPill value={centre.status} tone={isCritical ? "bad" : "good"} /></div><div className="mt-7 flex items-end justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.14em] text-muted-foreground">Current stock</p><p data-testid={`text-stock-${centre.id}`} className="mt-1 font-display text-3xl font-bold">{centre.currentQuantity.toFixed(1)} <span className="font-sans text-sm font-semibold text-muted-foreground">kg</span></p></div><p className="font-mono text-xs text-muted-foreground">of {centre.capacity.toFixed(0)} kg</p></div><div className="mt-4 h-3 overflow-hidden rounded-full bg-secondary"><div className={`h-full rounded-full transition-all ${fill >= 90 ? "bg-destructive" : fill >= 70 ? "bg-[#e6a14b]" : "bg-primary"}`} style={{ width: `${fill}%` }} /></div><div className="mt-2 flex items-center justify-between text-xs text-muted-foreground"><span>{fill.toFixed(0)}% filled</span><span className="flex items-center gap-1">{isCritical ? <TriangleAlert className="h-3.5 w-3.5 text-destructive" /> : null}{isCritical ? "Pickup recommended" : `${(centre.capacity - centre.currentQuantity).toFixed(1)} kg available`}</span></div><Button variant="quiet" size="sm" className="mt-5 w-full" onClick={() => window.open(`https://www.google.com/maps/search/?api=1&query=${centre.lat},${centre.long}`, "_blank")} testId={`button-map-centre-${centre.id}`}><MapPin className="h-3.5 w-3.5" /> View on map</Button></article> })}</div>}</section>;
}