import { ArrowUpRight, BarChart3, Leaf, MapPin, PackageOpen, Recycle, Truck } from "lucide-react";
import { Link } from "wouter";
import { useGetDashboard } from "@workspace/api-client-react";
import { MetricCard, MiniBarChart, QueryError, QueryLoading, StatusPill } from "@/components/ui-kit";

function formatNumber(value: number | undefined, digits = 1) { return value === undefined ? "—" : value.toLocaleString(undefined, { maximumFractionDigits: digits }); }

export default function Dashboard() {
  const dashboard = useGetDashboard();
  if (dashboard.isLoading) return <div className="mx-auto max-w-[1440px] space-y-6 p-5 sm:p-8"><div className="skeleton h-28 rounded-3xl" /><QueryLoading rows={5} /></div>;
  if (dashboard.isError || !dashboard.data) return <div className="mx-auto max-w-[1440px] p-5 sm:p-8"><QueryError onRetry={() => dashboard.refetch()} /></div>;
  const data = dashboard.data;
  return <section className="mx-auto max-w-[1440px] p-5 sm:p-8">
    <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="font-mono text-[11px] font-medium uppercase tracking-[.18em] text-primary">Tuesday, 24 September · morning brief</p><h1 data-testid="text-dashboard-heading" className="mt-2 max-w-xl font-display text-4xl font-bold leading-[1.02] tracking-[-.04em] sm:text-5xl">Keep the loop moving<span className="text-[#bfcc4d]">.</span></h1><p className="mt-3 max-w-xl text-sm leading-6 text-muted-foreground">A clear view of what your community has collected, where it is filling up, and what needs a hand next.</p></div><div className="flex items-center gap-2 rounded-2xl border border-[#b9dbba] bg-[#e9f5e9] px-4 py-3 text-sm font-semibold text-[#24563d]"><span className="h-2 w-2 rounded-full bg-[#5ca865]" /> Network healthy <span className="font-mono text-xs font-normal text-[#5ca865]">98.4%</span></div></div>
    <div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Plastic collected" value={`${formatNumber(data.totalCollected)} kg`} note="Across the active network" accent="lime" icon={<Recycle className="h-5 w-5" />} /><MetricCard label="Active centres" value={formatNumber(data.activeCentres, 0)} note="All locations reporting" accent="blue" icon={<MapPin className="h-5 w-5" />} /><MetricCard label="Pickup queue" value={formatNumber(data.pendingPickups, 0)} note="Requests waiting for a route" accent="orange" icon={<Truck className="h-5 w-5" />} /><MetricCard label="CO₂ kept out" value={`${formatNumber(data.co2Saved)} kg`} note="Estimated avoided emissions" accent="coral" icon={<Leaf className="h-5 w-5" />} /></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.35fr_.85fr]"><div className="rounded-2xl border border-card-border bg-card p-5 shadow-sm sm:p-6"><div className="flex items-start justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.16em] text-muted-foreground">Collection rhythm</p><h2 className="mt-1 font-display text-xl font-bold">Weekly collected</h2></div><span className="rounded-lg bg-secondary px-2.5 py-1 font-mono text-[10px] font-medium text-muted-foreground">KG / DAY</span></div><div className="mt-6"><MiniBarChart values={data.weeklyCollected ?? []} /></div><div className="mt-4 flex items-center gap-2 text-xs text-muted-foreground"><ArrowUpRight className="h-4 w-4 text-[#5ca865]" /><span><strong className="text-foreground">+12.8%</strong> compared with last week</span></div></div>
      <div className="rounded-2xl border border-card-border bg-card p-5 shadow-sm sm:p-6"><div className="flex items-start justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.16em] text-muted-foreground">Material mix</p><h2 className="mt-1 font-display text-xl font-bold">What is coming in</h2></div><BarChart3 className="h-5 w-5 text-primary" /></div><div className="mt-6 space-y-4">{(data.categoryBreakdown ?? []).map((item) => <div key={item.category} data-testid={`row-category-${item.category}`}><div className="mb-1.5 flex items-center justify-between text-xs"><span className="font-semibold">{item.category}</span><span className="font-mono text-muted-foreground">{item.quantity.toFixed(1)} kg <span className="text-foreground">({item.percentage}%)</span></span></div><div className="h-2 overflow-hidden rounded-full bg-secondary"><div className="h-full rounded-full bg-primary" style={{ width: `${item.percentage}%` }} /></div></div>)}</div></div></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.1fr_.9fr]"><div className="rounded-2xl border border-card-border bg-card p-5 shadow-sm sm:p-6"><div className="flex items-center justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.16em] text-muted-foreground">Live feed</p><h2 className="mt-1 font-display text-xl font-bold">Recent activity</h2></div><Link href="/deposits" data-testid="link-view-activity" className="flex items-center gap-1 text-xs font-bold text-primary hover:underline">View all <ArrowUpRight className="h-3.5 w-3.5" /></Link></div><div className="mt-5 divide-y divide-border">{(data.recentActivity ?? []).slice(0, 5).map((activity) => <div key={activity.id} data-testid={`row-activity-${activity.id}`} className="flex items-start gap-3 py-3 first:pt-0"><span className="mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-secondary text-primary">{activity.kind.toLowerCase().includes("pickup") ? <Truck className="h-4 w-4" /> : <PackageOpen className="h-4 w-4" />}</span><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{activity.label}</p><p className="mt-0.5 text-xs text-muted-foreground">{activity.detail}</p></div><span className="shrink-0 font-mono text-[10px] text-muted-foreground">{new Date(activity.timestamp).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</span></div>)}</div></div><div className="rounded-2xl border border-primary bg-primary p-5 text-primary-foreground shadow-sm sm:p-6"><div className="flex items-center justify-between"><p className="font-mono text-[10px] uppercase tracking-[.16em] text-accent">Today’s focus</p><span className="rounded-lg bg-primary-foreground/10 px-2 py-1 font-mono text-[10px]">NEXT BEST ACTION</span></div><h2 className="mt-10 max-w-xs font-display text-3xl font-bold leading-tight">Clear the east-side pickup queue.</h2><p className="mt-3 max-w-sm text-sm leading-6 text-primary-foreground/70">Three centres are nearing their threshold. A route generated before 09:00 keeps the day on pace.</p><Link href="/routes" data-testid="link-focus-route" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-accent px-4 py-2.5 text-sm font-bold text-accent-foreground hover:brightness-95">Open route planner <ArrowUpRight className="h-4 w-4" /></Link></div></div>
  </section>;
}