import { useMemo, useState } from "react";
import { ArrowUpRight, Clock3, PackageCheck, Search, Truck } from "lucide-react";
import { useListPickups } from "@workspace/api-client-react";
import { Button, EmptyState, QueryError, QueryLoading, StatusPill } from "@/components/ui-kit";

export default function Pickups() {
  const pickups = useListPickups();
  const [filter, setFilter] = useState("All requests");
  const [search, setSearch] = useState("");
  const items = useMemo(() => (pickups.data ?? []).filter((item) => `${item.centreName} ${item.priority}`.toLowerCase().includes(search.toLowerCase()) && (filter === "All requests" || item.status === filter)), [pickups.data, search, filter]);
  return <section className="mx-auto max-w-[1440px] p-5 sm:p-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="font-mono text-[11px] uppercase tracking-[.18em] text-primary">Logistics control</p><h1 className="mt-2 font-display text-4xl font-bold tracking-[-.04em]">Pickup queue</h1><p className="mt-2 text-sm text-muted-foreground">A calm handoff between full centres and the next available truck.</p></div><Button variant="quiet" onClick={() => pickups.refetch()} testId="button-refresh-pickups"><Clock3 className="h-4 w-4" /> Refresh queue</Button></div>
    <div className="mt-8 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border border-card-border bg-card p-4 shadow-sm"><p className="font-mono text-[10px] uppercase tracking-[.14em] text-muted-foreground">Waiting</p><p className="mt-2 font-display text-3xl font-bold">{(pickups.data ?? []).filter((item) => item.status.toLowerCase().includes("pending")).length}</p></div><div className="rounded-2xl border border-card-border bg-card p-4 shadow-sm"><p className="font-mono text-[10px] uppercase tracking-[.14em] text-muted-foreground">High priority</p><p className="mt-2 font-display text-3xl font-bold text-[#9a3d31]">{(pickups.data ?? []).filter((item) => item.priority.toLowerCase() === "high").length}</p></div><div className="rounded-2xl border border-card-border bg-card p-4 shadow-sm"><p className="font-mono text-[10px] uppercase tracking-[.14em] text-muted-foreground">Total weight</p><p className="mt-2 font-display text-3xl font-bold">{(pickups.data ?? []).reduce((sum, item) => sum + item.quantity, 0).toFixed(1)} <span className="font-sans text-sm font-semibold text-muted-foreground">kg</span></p></div></div>
    <div className="mt-6 rounded-2xl border border-card-border bg-card shadow-sm"><div className="flex flex-col gap-3 border-b border-border p-4 sm:flex-row sm:items-center sm:justify-between"><div className="relative flex-1 sm:max-w-xs"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><input data-testid="input-search-pickups" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search queue" className="w-full rounded-xl border border-input bg-background py-2.5 pl-9 pr-3 text-sm outline-none focus:ring-2 focus:ring-ring" /></div><select data-testid="select-pickup-status" value={filter} onChange={(e) => setFilter(e.target.value)} className="rounded-xl border border-input bg-background px-3 py-2.5 text-sm font-semibold outline-none"><option>All requests</option><option>Pending</option><option>Scheduled</option><option>Completed</option></select></div>{pickups.isLoading ? <div className="p-4"><QueryLoading rows={4} /></div> : pickups.isError ? <div className="p-4"><QueryError onRetry={() => pickups.refetch()} /></div> : items.length === 0 ? <div className="p-4"><EmptyState title="Queue is clear" detail="No pickup requests match these filters. That's a good shift." /></div> : <div className="divide-y divide-border">{items.map((item, index) => <div key={item.id} data-testid={`row-pickup-${item.id}`} className="flex flex-col gap-4 p-5 transition-colors hover:bg-secondary/40 sm:flex-row sm:items-center"><div className="flex min-w-0 flex-1 items-center gap-4"><span className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl ${item.priority.toLowerCase() === "high" ? "bg-[#f3c6bc] text-[#85372d]" : "bg-secondary text-primary"}`}><PackageCheck className="h-5 w-5" /></span><div className="min-w-0"><h2 className="truncate text-sm font-bold">{item.centreName}</h2><p className="mt-1 text-xs text-muted-foreground">Request PL-{item.id.slice(-4).toUpperCase()} · added {new Date(item.createdAt).toLocaleDateString(undefined, { day: "2-digit", month: "short" })}</p></div></div><div className="flex items-center gap-6 sm:justify-end"><div><p className="font-mono text-lg font-medium">{item.quantity.toFixed(1)} kg</p><p className="text-[10px] uppercase tracking-[.1em] text-muted-foreground">ready to move</p></div><StatusPill value={item.priority} /><StatusPill value={item.status} /><button data-testid={`button-pickup-details-${item.id}`} className="rounded-lg p-2 text-muted-foreground hover:bg-secondary hover:text-primary" onClick={() => window.alert(`Pickup ${item.id}: ${item.centreName}`)} aria-label={`View pickup ${index + 1}`}><ArrowUpRight className="h-4 w-4" /></button></div></div>)}</div>}</div><div className="mt-5 flex items-center gap-2 text-xs text-muted-foreground"><Truck className="h-4 w-4 text-primary" /> Pickup status is shared with drivers as routes are generated.</div></section>;
}