import { useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { getGetCreditsQueryKey, getListRewardsQueryKey, useGetCredits, useListRewards, useRedeemReward } from "@workspace/api-client-react";
import { CircleCheck, Gift, Sparkles } from "lucide-react";
import { useAuth } from "@/context/auth-context";

export default function Rewards() {
  const { user } = useAuth();
  const queryClient = useQueryClient();
  const credits = useGetCredits({ query: { enabled: user?.role === "citizen", queryKey: getGetCreditsQueryKey() } });
  const rewards = useListRewards({ query: { enabled: user?.role === "citizen", queryKey: getListRewardsQueryKey() } });
  const redeem = useRedeemReward();
  const [notice, setNotice] = useState("");
  if (user?.role !== "citizen") return <section className="mx-auto max-w-3xl p-8"><div className="rounded-2xl border border-border bg-card p-6"><h1 className="font-display text-2xl font-bold">Citizen rewards</h1><p className="mt-2 text-sm text-muted-foreground">Sign in as a citizen to view and redeem credits.</p></div></section>;
  return <section className="mx-auto max-w-[1200px] p-5 sm:p-8"><div><p className="font-mono text-[11px] uppercase tracking-[.18em] text-primary">Your impact, returned</p><h1 className="mt-2 font-display text-4xl font-bold tracking-[-.04em]">Rewards</h1><p className="mt-2 max-w-xl text-sm text-muted-foreground">Every deposit keeps material in the loop. Use your credits to fund visible change in the community.</p></div><div className="mt-8 rounded-2xl bg-primary p-6 text-primary-foreground sm:p-8"><div className="flex items-center gap-2 text-accent"><Sparkles className="h-5 w-5" /><span className="font-mono text-[10px] uppercase tracking-[.16em]">Available to redeem</span></div><p className="mt-3 font-display text-5xl font-bold">{credits.data?.availableCredits ?? 0}</p><p className="mt-1 text-sm text-primary-foreground/70">credits available · {credits.data?.totalEarned ?? 0} earned to date</p></div>{notice ? <div className="mt-5 rounded-xl border border-[#b9dbba] bg-[#e9f5e9] px-4 py-3 text-sm font-semibold text-[#24563d]"><CircleCheck className="mr-2 inline h-4 w-4" />{notice}</div> : null}<div className="mt-8 grid gap-4 md:grid-cols-3">{(rewards.data ?? []).map((reward) => <article key={reward.id} className="rounded-2xl border border-card-border bg-card p-5 shadow-sm"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-secondary text-primary"><Gift className="h-5 w-5" /></div><h2 className="mt-6 font-display text-xl font-bold">{reward.name}</h2><p className="mt-2 min-h-12 text-sm leading-6 text-muted-foreground">{reward.description}</p><div className="mt-6 flex items-center justify-between gap-3 border-t border-border pt-4"><span className="font-mono text-sm font-bold text-primary">{reward.creditCost} credits</span><button disabled={(credits.data?.availableCredits ?? 0) < reward.creditCost || redeem.isPending} onClick={() => redeem.mutate({ data: { rewardId: reward.id } }, { onSuccess: () => { setNotice(`${reward.name} redeemed successfully.`); queryClient.invalidateQueries({ queryKey: getGetCreditsQueryKey() }); queryClient.invalidateQueries({ queryKey: getListRewardsQueryKey() }); }, onError: () => setNotice("You do not have enough credits for that reward.") })} className="rounded-lg bg-primary px-3 py-2 text-xs font-bold text-primary-foreground disabled:cursor-not-allowed disabled:opacity-40">Redeem</button></div></article>)}</div></section>;
}